// @ts-check
// scripts/lib/gen-tokens.js - the brand colour tokens, as a CSS file and a JSON file.
//
// WHAT. The brand's colours are written once, as a law, in brand/config/color-system.md. Anything that
// needs the palette (a web page, a chart, a deck) reads it from brand/tokens/ instead: tokens.json,
// which is tracked, and tokens.css, which is gitignored and rendered again on every generator run.
//
// HOW. Both renderers take the token table read-sources.js already parsed from the law file, the model's
// colorTokens: a Map from token name to hex, in the law's order. tokensCss writes one custom property per
// token inside :root, named --color-<name in lower kebab case>, under a comment saying where it comes
// from. tokensJson writes { _generated, _source, tokens } with the names as the law writes them, two-space
// indented, ending in a line break.
//
// NEVER. Reads the law file itself: read-sources.js is the one reader of it, so the generator and the
// validator cannot parse it two ways. Refuses or renames two token names that kebab to the same property;
// both are written, and the generator tests pin that as it is. Writes a file: the caller stages the text.
//
// Usage: module only - const { tokensCss, tokensJson, CSS_REL, JSON_REL } = require('./gen-tokens');
'use strict';

const CSS_REL = 'brand/tokens/tokens.css';
const JSON_REL = 'brand/tokens/tokens.json';
const HEADER = 'GENERATED by scripts/generate-alex.js from brand/config/color-system.md - never hand-edit';

/** @typedef {Pick<import('./read-sources').ColorTokens, 'tokens'>} ColorTokens the token table, name to hex */

/**
 * A token name as a CSS custom-property suffix: lower case, every run of other characters one hyphen.
 * @param {string} name
 */
const kebab = (name) =>
  name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

/**
 * brand/tokens/tokens.css.
 * @param {ColorTokens} colorTokens
 * @returns {string}
 */
function tokensCss(colorTokens) {
  const lines = [
    `/* ${HEADER}.`,
    '   One custom property per named token in the color law (core palette + extended palette).',
    '   Regenerate with: node scripts/generate-alex.js --only=tokens */',
    ':root {'
  ];
  for (const [name, hex] of colorTokens.tokens) lines.push(`  --color-${kebab(name)}: ${hex};`);
  lines.push('}', '');
  return lines.join('\n');
}

/**
 * brand/tokens/tokens.json.
 * @param {ColorTokens} colorTokens
 * @returns {string}
 */
function tokensJson(colorTokens) {
  /** @type {{ _generated: string, _source: string, tokens: Record<string, string> }} */
  const out = {
    _generated: HEADER,
    _source: 'brand/config/color-system.md',
    tokens: {}
  };
  for (const [name, hex] of colorTokens.tokens) out.tokens[name] = hex;
  return `${JSON.stringify(out, null, 2)}\n`;
}

module.exports = { CSS_REL, JSON_REL, HEADER, tokensCss, tokensJson };
